<#
  _resolve_docs_path.ps1 -- shared docs/ subfolder resolver (2026-07-01 docs/ reorg pilot).

  Four categories, one folder each, under providers/<PROVIDER>/docs/:
    tracking/     -- hand-relevant, updated every version (STATUS, SQVR, BUILD_NOTES,
                      CHANGELOG, JSON_INVENTORY, DEX_TICKET, BUILD_MANIFEST, PENDING_UPDATES)
    reports/      -- auto-generated by build_report.ps1's steps, fully reproducible
                      (VALIDATOR_REPORT, LAYOUT_REPORT/.html, QUERY_REPORT, PICKLIST_REPORT,
                      LABEL_REVIEW, CAD_AUDIT, METADATA_AUDIT, VERIFY_REPORT,
                      RESPONSE_SIMULATION, SUPPORTED_QUERY_AUDIT, LINT_REPORT,
                      TEST_VALIDATION, TEST_MATRIX)
    reference/    -- derived from metadata XML, semi-static (METADATA_REFERENCE,
                      SUPPORTED_QUERIES)
    deliverables/ -- officer/tester-facing artifacts, not consumed by tooling logic
                      (OFFICER_GUIDE)

  MIGRATION MODEL (no per-provider flag file needed): a provider has migrated if ANY of
  its 4 category folders already exists. Get-DocsCategoryDir then:
    - returns the category folder if it already exists
    - creates + returns it if a SIBLING category folder exists (provider is migrated,
      this category just hasn't been touched yet -- e.g. a provider with no officer
      guide yet still counts as migrated once tracking/ exists)
    - falls back to the flat docs/ folder if NONE of the 4 exist (legacy, unmigrated
      provider -- current behavior, unchanged)
  This lets NJ_NJCJIS (migrated) and every other provider (not yet) share the exact same
  tool code with zero per-provider special-casing.

  NEVER used for the legacy docs/base + docs/mc split (BASE/MC JSON variant providers) --
  that is a separate, orthogonal, soon-obsolete scheme and is untouched by this resolver.

  Usage (dot-source, matches _resolve_provider_json.ps1's convention):
    . "$PSScriptRoot\_resolve_docs_path.ps1"
    $trackingDir = Get-DocsCategoryDir $provDir 'tracking'
    $statusPath  = Join-Path $trackingDir "${Provider}_STATUS.txt"
#>

$script:DocsCategories = @('tracking', 'reports', 'reference', 'deliverables')

function Get-DocsCategoryDir([string]$provDir, [string]$category) {
    if ($script:DocsCategories -notcontains $category) {
        throw "Get-DocsCategoryDir: unknown category '$category' (expected one of: $($script:DocsCategories -join ', '))"
    }
    $flatDocs = Join-Path $provDir "docs"
    $targetDir = Join-Path $flatDocs $category
    if (Test-Path $targetDir) { return $targetDir }

    $migrated = $false
    foreach ($c in $script:DocsCategories) {
        if (Test-Path (Join-Path $flatDocs $c)) { $migrated = $true; break }
    }
    if ($migrated) {
        New-Item -ItemType Directory -Path $targetDir -Force | Out-Null
        return $targetDir
    }
    return $flatDocs
}

# Convenience: resolve the full file path in one call.
function Get-DocsPath([string]$provDir, [string]$category, [string]$fileName) {
    return Join-Path (Get-DocsCategoryDir $provDir $category) $fileName
}

# Read-side helper: a file may exist in EITHER the new category folder or the flat
# legacy folder (e.g. right after a partial migration, or when auditing a not-yet-fully-
# migrated provider). Checks the resolved category dir first, then flat docs/ as fallback,
# so reads never silently miss a file that hasn't been physically moved yet.
function Find-DocsPath([string]$provDir, [string]$category, [string]$fileName) {
    $preferred = Get-DocsPath $provDir $category $fileName
    if (Test-Path $preferred) { return $preferred }
    $flatFallback = Join-Path (Join-Path $provDir "docs") $fileName
    if (Test-Path $flatFallback) { return $flatFallback }
    return $preferred  # neither exists -- return the preferred (category) path as the canonical "should be here"
}

# Report-tool fingerprint: a stable hash of the tool files whose output BUILD_MANIFEST gates.
# build_report stamps it into the manifest; enforce compares it. When a report-generating tool
# changes but the JSON does not, the manifest's sourceSha256 still matches, so enforce would
# otherwise trust a report produced by the OLD tool (audit C3 finding 2026-07-24: fresh
# verify_build = 16 PASS vs committed 15). Including the fingerprint in enforce's trust condition
# makes a tool change trigger the SAME auto-heal (re-run build_report) as a JSON change. Defined
# ONCE here (both build_report + enforce dot-source this module) so the two can never diverge.
function Get-ReportToolFingerprint([string]$toolDir) {
    $files = @('validate.ps1','verify_build.ps1','audit_cad.ps1','audit_metadata.ps1','audit_supported_queries.ps1') | Sort-Object
    $parts = foreach ($f in $files) {
        $p = Join-Path $toolDir $f
        if (Test-Path $p) { (Get-FileHash -Path $p -Algorithm SHA256).Hash } else { 'MISSING' }
    }
    return ($parts -join ':')
}
